# Generated by Django 5.1.7 on 2025-04-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_playlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
